import Header from '@/components/ui/Header'
import localFont from 'next/font/local'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Konnect = localFont({
  src: [
    {
      path: './Konnect-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './Konnect-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './Konnect-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './Konnect-Medium.otf',
      weight: '500',
      style: 'normal',
    },
  ],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={Konnect.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
